wagtail/mysite/mysite/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path('', include('allauth.urls')),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path('__debug__/', include(debug_toolbar.urls)),
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

wagtail/mysite/wikifisc/urls.py
from django.urls import path

from . import views

app_name = 'wikifisc'

"""
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
"""
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

wagtail/mysite/blog/models.py
from django.db import models
from modelcluster.fields import ParentalKey
from wagtail.core.models import Page, Orderable
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index
# Create your models here.

class BlogIndexPage(Page):
    intro = RichTextField(blank=True)

    def get_context(self, request):
        # Update context to include only published posts, ordered by reverse-chron
        context = super().get_context(request)
        blogpages = self.get_children().live().order_by('-first_published_at')
        context['blogpages'] = blogpages
        return context


class BlogPage(Page):
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = RichTextField(blank=True)

    def main_image(self):
        gallery_item = self.gallery_images.first()
        if gallery_item:
            return gallery_item.image
        else:
            return None


    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        FieldPanel('intro'),
        FieldPanel('body', classname="full"),
        InlinePanel('gallery_images', label="Gallery images"),
    ]


class BlogPageGalleryImage(Orderable):
    page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

wagtail/mysite/flex/models.py
"""Flexible page"""
from streams import blocks
from django.db import models
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel
from wagtail.core.models import Page
from wagtail.core.fields import StreamField
# Create your models here.


class FlexPage(Page):

    template = "flex/flex_page.html"

    content = StreamField(
        [
            ("title_and_text", blocks.TitleAndTextBlock()),
            ("full_richtext", blocks.RichtextBlock()),
            ("simple_richtext", blocks.SimpleRichtextBlock()),
            ("cards", blocks.CardBlock()),
            ("cta", blocks.CTABlock()),
        ],
        null=True,
        blank=True
    )
    subtitle = models.CharField(max_length=100, blank=True, null=True)

    content_panels = Page.content_panels + [
        FieldPanel("subtitle"),
        StreamFieldPanel("content")
    ]

    class Meta:
        verbose_name = "Flex Page"
        verbose_name_plural = "Flex Pages"

wagtail/mysite/home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField, StreamField
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel, StreamFieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from streams import blocks


class HomePage(Page):
    body = RichTextField(blank=True)
    template = "home/home_page.html"
    max_count = 1

    banner_title = models.CharField(max_length=100, blank=False, null=True)
    banner_subtitle = RichTextField(features=["bold","italic"])
    banner_image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name="+"
    )
    banner_cta = models.ForeignKey(
        "wagtailcore.Page",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+"
    )
    content = StreamField(
        [
            ("cta", blocks.CTABlock()),
        ],
        null=True,
        blank=True,
    )
    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
        FieldPanel("banner_title"),
        FieldPanel("banner_subtitle"),
        ImageChooserPanel("banner_image"),
        PageChooserPanel("banner_cta"),
        StreamFieldPanel("content"),
    ]

    class Meta:

        verbose_name = "Home Page"
        verbose_name_plural = "Home Pages"

wagtail/mysite/streams/models.py
from django.db import models

# Create your models here.

wagtail/mysite/wikifisc/models.py
from django.db import models

# Create your models here.

"""Flexible page."""
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page
from wiki.sites import WikiSite


class Wiki(Page):
    """Flexibile page class."""

    template = "wiki/base.html"

    subtitle = models.CharField(max_length=100, null=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("subtitle"),
    ]

    class Meta:  # noqa 
        verbose_name = "Wiki page"
        verbose_name_plural = "Wiki Pages"


class MyWikiSite(WikiSite):
    pass

wagtail/mysite/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

wagtail/mysite/wikifisc/views.py
from django.shortcuts import render

# Create your views here.

wagtail/mysite/blog/templates/blog/blog_index_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-blogindexpage{% endblock %}

{% block content %}
    <h1>{{ page.title }}</h1>

    <div class="intro">{{ page.intro|richtext }}</div>
{% for post in blogpages %}
    {% with post=post.specific %}
        <h2><a href="{% pageurl post %}">{{ post.title }}</a></h2>

        {% with post.main_image as main_image %}
            {% if main_image %}{% image main_image fill-160x100 %}{% endif %}
        {% endwith %}

        <p>{{ post.intro }}</p>
        {{ post.body|richtext }}
    {% endwith %}
{% endfor %}
{% endblock %}

wagtail/mysite/blog/templates/blog/blog_page.html
{% extends "base.html"  %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-blogpage{% endblock %}

{% block content %}
    <h1>{{ self.title }}</h1>
    <p class="meta">{{ page.date }}</p>

    <div class="intro">{{ page.intro }}</div>

    {{ page.body|richtext }}
    
    {% for item in page.gallery_images.all %}
        <div style="float: left; margin: 10px">
            {% image item.image fill-320x240 %}
            <p>{{ item.caption }}</p>
        </div>
    {% endfor %}

    <p><a href="{{ page.get_parent.url }}">Return to blog</a></p>

{% endblock %}

wagtail/mysite/home/templates/home/home_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}

    {% image self.banner_image fill-900x400 as img %}

    <div class="jumbotron" style="background-image: url('{{ img.url }}'); background-size: contain; color: #fff !important">
        <h1 class="display-4">{{ self.banner_title }}</h1>
        <div class="lead">{{ self.banner_subtitle|richtext }}</div>
        {% if self.banner_cta %}
            <a class="btn btn-primary btn-lg" href="#" role="button">@todo</a>
        {% endif %}
    </div>    
    {% for block in page.content %}
        {% include_block block %}
    {%endfor%}
{% endblock %}

wagtail/mysite/mysite/templates/base.html
{% load static wagtailuserbar %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" href="https://bootswatch.com/4/superhero/bootstrap.min.css" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/mysite.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">IFISC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarColor01">
                <!--
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                  </div>
                </li>
              </ul>
              
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
              -->
            </div>
          </nav>
        {% block content %}
        {% endblock %}

        {# Global javascript #}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/mysite.js' %}"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

wagtail/mysite/mysite/templates/flex/flex_page.html
{% extends "base.html" %}
{%load wagtailcore_tags %}
{%block content %}
    <div>
        {{self.subtitle}}
    </div>

    {% for block in page.content %}
        {% include_block block %}
    {%endfor%}
{%endblock %}

wagtail/mysite/mysite/templates/streams/card_block.html
{% load wagtailimages_tags %}

<div class="container mb-sm-5 mt-sm-5">
    <h1 class="text-center mb-sm-5">{{ self.title }}</h1>
    <div class="card-deck">
        {% for card in self.cards %}
            {% image card.image fill-300x200 as img %}
            <div class="card">
                <img src="{{ img.url }}" alt="{{ img.alt }}" class="card-img-top" />
                <div class="card-body">
                    <h5 class="card-title">{{ card.title }}</h5>
                    <p class="card-text">{{ card.text }}</p>
                    {% if card.button_page %}
                        <a href="{{ card.button_page.url }}" class="btn btn-primary">
                            Learn More
                        </a>
                    {% elif card.button_url %}
                        <a href="{{ card.button_url }}" class="btn btn-primary">
                            Learn More
                        </a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

wagtail/mysite/mysite/templates/streams/cta_block.html
{% load wagtailcore_tags %}

<div class="container mb-sm-5 mt-sm-5">
    <div class="row">
        <div class="col-md-5 offset-md-1 col-sm-12">
            <h1>{{ self.title }}</h1>
            {{ self.text|richtext }}

            {% if self.button_page %}
                <a href="{{ self.button_page.url }}">{{ self.button_text }}</a>
            {% elif self.button_url %}
                <a href="{{ self.button_url }}">{{ self.button_text }}</a>
            {% endif %}
        </div>
    </div>
</div> 

wagtail/mysite/mysite/templates/streams/richtext_block.html
{{ self }}

wagtail/mysite/mysite/templates/streams/title_and_text_block.html
<div>
    <h2>{{ self.title }}</h2>
    <p>{{ self.text }}</p>
</div>

wagtail/mysite/mysite/templates/wiki/base.html
{% extends "admin/base_site.html" %}
{% block content %}
{% load crispy_forms_tags %}

{% load sekizai_tags i18n wiki_tags static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <title>{% block wiki_pagetitle %}{% endblock %}{% block wiki_site_title %} - django-\/\/  i K |{% endblock %}</title>
   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="www.django-wiki.org">
    
    <!-- Le styles -->
    <link href="{% static "wiki/bootstrap/css/wiki-bootstrap.min.css" %}" rel="stylesheet">
   
    
    
  </head>
  
  <body>

    {% block wiki_body %}

    {% block wiki_navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    {% block wiki_header_branding %}
          <a class="navbar-brand" href="{% url 'wiki:root' %}">django-\/\/ i K |</a>
    {% endblock %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
    {% block wiki_header_navlinks %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">{% trans "Home" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/django-wiki/django-wiki" target="_blank">{% trans "About" %}</a>
        </li>
    </ul>
    {% endblock %}
      {% if user.is_authenticated %}
              <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">
                  <span class="badge badge-light">0</span>
                  {{ user }}
                  <b class="caret"></b>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if "ACCOUNT_HANDLING"|wiki_settings %}
                    <a href="{% url 'wiki:profile_update' %}" class="dropdown-item">
                      <i class="fa fa-cog"></i>
                      {% trans "Account Settings" %}
                    </a>
                  {% endif %}
                    <a href="{{ "LOGOUT_URL"|wiki_settings }}" class="dropdown-item">
                      <i class="fa fa-power-off"></i>
                      {% trans "Log out" %}
                    </a>
                  {% if user.is_superuser %}
                    <a href="{% url 'wiki:deleted_list' %}" class="dropdown-item">
                      <i class="fa fa-trash"></i>
                      {% trans "Deleted articles" %}
                    </a>
                  {% endif %}
                  {% if "wiki.plugins.notifications"|plugin_enabled %}
                    {% include "wiki/plugins/notifications/menubaritem.html" %}
                  {% endif %}
                  {% if "wiki.plugins.globalhistory"|plugin_enabled %}
                    {% include "wiki/plugins/globalhistory/menubaritem.html" %}
                  {% endif %}
                </div>
              </li>
              </ul>
      {% else %}
      <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" href="{% login_url as wiki_login_url %}{{ wiki_login_url }}">{% trans "Log in" %}</a>
        </li>
        {% if "ACCOUNT_HANDLING"|wiki_settings %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'wiki:signup' %}">{% trans "Sign up" %}</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}


      <form class="form-inline" method="GET" action="{% spaceless %}
            {% if article or urlpath %}
                {% url 'wiki:search' article_id=article.id path=urlpath.path %}
              {% else %}
                {% url 'wiki:search' %}
              {% endif %}
            {% endspaceless %}"
      >
      <div class="input-group">
        <input type="search" class="form-control" aria-label="Search" name="q" placeholder="{% spaceless %}
                {% if article or urlpath %}
                   {% trans "Search from current article..." %}
                {% else %}
                  {% trans "Search whole wiki..." %}
                {% endif %}
              {% endspaceless %}" />
        <div class="input-group-append">
          <button class="btn btn-outline-light my-sm-0" type="submit"><span class="fa fa-search"></span></button>
        </div>
        </div>
      </form>
    </div>

  </div>
  </nav>
    {% endblock %}

    <div class="container" style="margin-top: 60px;">

      {% wiki_messages %}

      <!-- Reserved for breadcrumbs -->
      {% block wiki_breadcrumbs %}{% endblock %}

      <!-- Main page contents go here -->
      {% block wiki_contents %}{% endblock %}

      <footer id="wiki-footer">
        <hr />
        {% block wiki_footer_logo %}
        <a href="https://github.com/django-wiki/django-wiki" class="float-right"><img src="{% static "wiki/img/github_icon.png" %}" /></a>
        {% endblock %}
        {% block wiki_footer_prepend %}
        {% endblock %}
        <p>{% blocktrans %}Powered by <a href="http://www.django-wiki.org">django-wiki</a>, an open source application under the <a href="http://www.gnu.org/licenses/quick-guide-gplv3.html">GPLv3</a> license. Let knowledge be the cure.{% endblocktrans %}</p>
        <div class="clearfix"></div>
      </footer>
      </div>

    </div> <!-- /container -->


    <form>
      {{ my_formset|crispy }}
      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
      </div>
      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}

    <script src="{% static "wiki/js/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "wiki/js/core.js" %}"></script>
    <script src="{% static "wiki/js/popper.js" %}"></script>
    <script src="{% static "wiki/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <script src="{% static "wiki/js/respond.min.js" %}"></script>


  </body>
</html>
{% endblock %}
{% render_block "css" %}
{% render_block "js" %}

wagtail/mysite/search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1>Search</h1>

    <form action="{% url 'search' %}" method="get">
        <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
        <input type="submit" value="Search" class="button">
    </form>

    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
                    {% if result.search_description %}
                        {{ result.search_description }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        {% if search_results.has_previous %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
        {% endif %}

        {% if search_results.has_next %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
        {% endif %}
    {% elif search_query %}
        No results found
    {% endif %}
{% endblock %}